"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const translations: Record<Language, Record<string, any>> = {
  es: {
    "nav.start": "Inicio",
    "nav.what_we_do": "¿Qué hacemos?",
    "nav.platform": "Plataforma",
    "nav.sectors": "Sectores",
    "nav.pricing": "Precios",
    "nav.contact": "Contactar",
    "hero.title1": "Tu negocio no necesita trabajar más,",
    "hero.title2": "necesita trabajar solo.",
    "hero.subtitle": "Synora es la solución de automatización diseñada para empresas que quieren crecer sin complicarse la vida. Transformamos procesos manuales en flujos inteligentes.",
    "hero.cta1": "Ver Soluciones",
    "hero.cta2": "Agendar Auditoría",
    "pillars.title1": "Trabaja menos,",
    "pillars.title2": "produce más.",
    "pillars.subtitle": "Transformamos los procesos rotos que consumen tu tiempo diario en flujos de trabajo inteligentes que funcionan de forma autónoma.",
    "pillars.card1.title": "Automatización 24/7",
    "pillars.card1.stat": "+10h liberadas/semana",
    "pillars.card1.desc": "Lo repetitivo se gestiona solo y en segundo plano sin intervención manual. Mensajes, citas y avisos en piloto automático.",
    "pillars.card2.title": "Orden Absoluto",
    "pillars.card2.stat": "-40% carga operativa",
    "pillars.card2.desc": "Transformamos datos dispersos en dashboards claros. Reduce la carga operativa de tu equipo centralizando la información.",
    "pillars.card3.title": "Control Predictivo",
    "pillars.card3.stat": "0 dependencia técnica",
    "pillars.card3.desc": "Ejecución perfecta siempre. Los procesos se estandarizan eliminando errores humanos y dependencia técnica del personal.",
    "pricing.badge": "Inversión Inteligente",
    "pricing.title": "Planes de Automatización",
    "pricing.subtitle": "Escala tu negocio con sistemas que trabajan por ti. Sin complicaciones técnicas, solo resultados.",
    "pricing.recommended": "Recomendado",
    "pricing.month": "/mes",
    "pricing.setup": "Setup inicial",
    "pricing.audit": "Auditoría Recomendada (Desde 200€)",
    "pricing.disclaimer": "* Los planes y módulos incluyen un volumen generoso de tokens de Inteligencia Artificial para un uso estándar. En caso de uso masivo, el precio se ajustará proporcionalmente al consumo real.",
    "pricing.foundational.title": "Infraestructura y Setup (Pago Único)",
    "pricing.foundational.subtitle": "Construimos la base sólida para tu automatización.",
    "pricing.foundational.web.title": "Web a Medida & CRM",
    "pricing.foundational.web.price": "Desde 349€",
    "pricing.foundational.web.desc": "Tu escaparate premium listo para IA.",
    "pricing.foundational.iso.title": "Consultoría & ISO 9001",
    "pricing.foundational.iso.price": "Desde 200€",
    "pricing.foundational.iso.desc": "Calidad certificada y procesos IA.",
    "pricing.modules.title": "Módulos y Packs de Automatización",
    "pricing.modules.subtitle": "Añade soluciones verticales para tu sector o herramientas individuales a la carta para potenciar tu negocio.",
    "pricing.modules.all": "Ver todas las funcionalidades individuales a la carta",
    "comparison.badge": "Comparativa",
    "comparison.title1": "La diferencia es",
    "comparison.title2": "el tiempo.",
    "comparison.without": "Sin Synora",
    "comparison.with": "Con Synora",
    "footer.title1": "Competitividad",
    "footer.title2": "sin complicaciones.",
    "footer.subtitle": "Estamos listos para hacer que tu negocio trabaje solo. ¿Tú lo estás?",
    "footer.cta": "Contactar con Synora",
    "footer.rights": "© 2026 Synora Solutions. Todos los derechos reservados.",
    "footer.legal": "Aviso Legal",
    "footer.privacy": "Privacidad",
    "footer.cookies": "Cookies",
    "cookie.title": "Panel de Cookies",
    "cookie.desc": "Utilizamos cookies para mejorar tu experiencia. Al navegar aceptas nuestra política.",
    "cookie.accept": "Aceptar todas",
    "cookie.settings": "Configurar",
    "home.methodology": "Metodología Synora",
    "home.problem_solution": "Del problema a la solución",
    "home.step01.title": "Detectamos el atasco",
    "home.step01.desc": "Analizamos cómo trabajas hoy para identificar procesos que roban tiempo y generan errores.",
    "home.step02.title": "Diseñamos el flujo",
    "home.step02.desc": "Definimos activadores, pasos y gestión de excepciones. Validamos la lógica contigo.",
    "home.step03.title": "Conectamos sistemas",
    "home.step03.desc": "Integramos Synora con tu CRM, agenda y herramientas actuales. Sin cambiar de software.",
    "home.step04.title": "Puesta en marcha",
    "home.step04.desc": "Lanzamos el sistema y monitorizamos resultados. Tu negocio empieza a trabajar solo.",
    "home.platform.badge": "Tu Centro de Control",
    "home.platform.title1": "Una única plataforma para",
    "home.platform.title2": "gobernarlo todo.",
    "home.platform.desc": "Olvídate de saltar entre 10 herramientas distintas. El Dashboard de Synora centraliza tus automatizaciones, embudos de venta, clientes y métricas clave en un solo lugar.",
    "home.platform.feat1": "Monitorización en tiempo real",
    "home.platform.feat2": "Integración con tu CRM actual",
    "home.platform.feat3": "Gestión de agentes y roles",
    "home.platform.cta": "Explorar el Dashboard interactivo",
    "home.ecosystem.badge": "Ecosistema de Industrias",
    "home.ecosystem.title1": "Especialización",
    "home.ecosystem.title2": "sectorial total.",
    "home.ecosystem.desc": "Aunque nuestra tecnología es transversal, hemos diseñado módulos específicos para los retos críticos de cada industria.",
    "home.sector.inmo.title": "Inmobiliarias",
    "home.sector.inmo.desc": "Captación de propietarios y Property Intelligence.",
    "home.sector.clinicas.title": "Clínicas Médicas",
    "home.sector.clinicas.desc": "Gestión de citas IA y recuperación de pacientes inactivos.",
    "home.sector.rest.title": "Restaurantes",
    "home.sector.rest.desc": "Libro de reservas inteligente y Guest Intelligence.",
    "home.sector.gym.title": "Fitness y Deporte",
    "home.sector.gym.desc": "Prevención de churn y altas de socios automatizadas.",
    "home.sector.ecomm.title": "E-commerce",
    "home.sector.ecomm.desc": "Atención al cliente 24/7 y recuperación de carritos.",
    "home.sector.legal.title": "Legal / Despachos",
    "home.sector.legal.desc": "Clasificación de documentos y triaje de expedientes.",
    "home.sector.custom.title": "¿Tu sector no aparece?",
    "home.sector.custom.desc": "Diseñamos soluciones personalizadas para cualquier flujo de trabajo.",
    "home.sector.custom.cta": "Consultar caso",
    "home.sector.cta": "Ver solución",
    "home.coming_soon": "Próximamente",
    "contact.badge": "Hablemos",
    "contact.title1": "Diseñemos tu",
    "contact.title2": "próximo salto.",
    "contact.subtitle": "¿Tienes un proceso que te quita el sueño? Cuéntanoslo y te diremos cómo podemos automatizarlo.",
    "contact.form.name": "Nombre",
    "contact.form.namePlaceholder": "Tu nombre",
    "contact.form.company": "Empresa",
    "contact.form.companyPlaceholder": "Nombre de tu empresa",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "hola@tuempresa.com",
    "contact.form.message": "¿Cómo podemos ayudarte?",
    "contact.form.messagePlaceholder": "Cuéntanos brevemente tu caso...",
    "contact.form.submit": "Enviar mensaje",
    "dashboard.badge": "Centro de Operaciones",
    "dashboard.hero.title1": "El cerebro de",
    "dashboard.hero.title2": "tu negocio.",
    "dashboard.hero.desc": "Centraliza, monitoriza y escala. El Dashboard de Synora no es solo un panel de control, es el núcleo donde la inteligencia artificial y tus procesos se encuentran.",
    "dashboard.feat1.title": "Control Total 24/7",
    "dashboard.feat1.desc": "Acceso instantáneo a todos tus procesos automatizados. Revisa el estado de tus leads, citas y operaciones en tiempo real desde cualquier dispositivo.",
    "dashboard.feat2.title": "Analítica Inteligente",
    "dashboard.feat2.desc": "No solo mostramos datos, te decimos qué significan. Identifica cuellos de botella y oportunidades de crecimiento con informes generados por IA.",
    "dashboard.feat3.title": "Gestión de Equipo",
    "dashboard.feat3.desc": "Asigna roles, monitoriza el rendimiento de tus colaboradores y centraliza la comunicación interna sin salir de la plataforma.",
    "dashboard.monitor.badge": "Monitorización Viva",
    "dashboard.monitor.title1": "Inteligencia en",
    "dashboard.monitor.title2": "tiempo real.",
    "dashboard.monitor.desc": "Observa cómo Synora procesa cada evento de tu negocio. Desde la entrada de un lead hasta la confirmación de una venta, todo ocurre bajo tu supervisión pero sin tu intervención.",
    "dashboard.monitor.latency": "Latencia",
    "dashboard.monitor.uptime": "Uptime",
    "dashboard.monitor.events": "Eventos/día",
    "dashboard.stats.time": "Ahorro de Tiempo",
    "dashboard.stats.leads": "Más Leads",
    "dashboard.stats.response": "Respuesta Media",
    "dashboard.stats.time_desc": "Automatizamos las tareas repetitivas para que tu equipo se enfoque en cerrar acuerdos reales.",
    "dashboard.stats.leads_desc": "Nuestra IA no descansa. Capta, filtra y califica prospectos las 24 horas del día, los 7 días de la semana.",
    "dashboard.stats.response_desc": "La velocidad de respuesta es clave. Synora atiende a tus clientes al instante, garantizando la máxima conversión.",
    "dashboard.connect.badge": "Conectividad sin límites",
    "dashboard.connect.title1": "El núcleo que une",
    "dashboard.connect.title2": "todo tu ecosistema.",
    "dashboard.connect.desc": "El dashboard no es un silo. Se integra con cada módulo y pack de Synora, además de tus herramientas actuales, para crear un flujo de trabajo fluido y sin fricciones.",
    "dashboard.connect.item1.title": "WebConnect",
    "dashboard.connect.item1.desc": "Sincronización bidireccional automática entre tu página web y el dashboard. Cada lead o cambio se refleja al instante.",
    "dashboard.connect.item2.title": "Módulos Sectoriales",
    "dashboard.connect.item2.desc": "Ya sea para inmobiliarias, clínicas o gimnasios, el dashboard adapta sus herramientas a las necesidades de tu industria.",
    "dashboard.connect.item3.title": "API & Webhooks",
    "dashboard.connect.item3.desc": "Conecta cualquier sistema externo. Si tiene una API, Synora puede hablar con ella y centralizar su gestión.",
    "dashboard.ecosystem.title1": "Ecosistema",
    "dashboard.ecosystem.title2": "Ilimitado.",
    "dashboard.ecosystem.desc": "Activa solo lo que necesitas. Nuestro dashboard es un sistema vivo que escala con bloques funcionales listos para ser desplegados.",
    "dashboard.ecosystem.custom": "¿Necesitas algo a medida?",
    "dashboard.ecosystem.custom_cta": "Desarrollar módulo personalizado",
    "dashboard.custom.title1": "Hecho",
    "dashboard.custom.title2": "100% para ti.",
    "dashboard.custom.desc": "No creemos en soluciones genéricas. Cada dashboard se configura y personaliza según los flujos de trabajo específicos de tu empresa para garantizar el máximo rendimiento.",
    "dashboard.custom.cta": "Solicitar personalización",
    "dashboard.custom.feat1": "Adaptable",
    "dashboard.custom.feat2": "Integraciones",
    "dashboard.custom.feat3": "Zero Configuración técnica",
    "dashboard.custom.feat4": "Dual Mode",
    "dashboard.security.title1": "Seguridad de",
    "dashboard.security.title2": "grado empresarial.",
    "dashboard.security.item1.title": "Encriptación AES-256",
    "dashboard.security.item1.desc": "Tus datos están protegidos con el estándar de cifrado más robusto de la industria, tanto en reposo como en tránsito.",
    "dashboard.security.item2.title": "Conformidad RGPD",
    "dashboard.security.item2.desc": "Cumplimos estrictamente con la normativa europea de protección de datos para tu tranquilidad y la de tus clientes.",
    "dashboard.security.item3.title": "Backups en Tiempo Real",
    "dashboard.security.item3.desc": "Réplicas automáticas en múltiples regiones para garantizar que tu negocio nunca se detenga.",
    "dashboard.mobile.badge": "Movilidad Total",
    "dashboard.mobile.title1": "Tu negocio,",
    "dashboard.mobile.title2": "en tu bolsillo.",
    "dashboard.mobile.desc": "El Dashboard de Synora ha sido diseñado con un enfoque \"responsive-first\". Accede a toda la potencia de tu centro de operaciones desde tu smartphone, tablet o escritorio sin perder ni una sola funcionalidad.",
    "dashboard.mobile.feat1": "Interfaz móvil optimizada",
    "dashboard.mobile.feat2": "Modo offline inteligente",
    "dashboard.mobile.feat3": "Notificaciones push en tiempo real",
    "admin.welcome": "Bienvenido de nuevo.",
    "admin.summary": "Aquí tienes un resumen de lo que está pasando en Synora.",
    "admin.view_site": "Ver sitio web",
    "admin.stats.posts": "Post Publicados",
    "admin.stats.drafts": "Borradores",
    "admin.stats.visits": "Visitas Totales",
    "admin.recent_posts": "Últimos Posts",
    "admin.logout": "Cerrar Sesión",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.posts": "Posts del Blog",
    "admin.nav.config": "Configuración",
    "planes.hero.title1": "Tu escala de",
    "planes.hero.title2": "crecimiento.",
    "planes.hero.desc": "Diseñamos planes que se adaptan al volumen real de tu negocio. Sin sorpresas, con todo incluido.",
    "planes.matrix.features": "Características",
    "planes.matrix.essential": "Plan Esencial",
    "planes.matrix.growth": "Plan Crecimiento",
    "planes.matrix.pro": "Plan Pro",
    "planes.matrix.from": "Desde",
    "planes.matrix.month": "mes",
    "planes.matrix.setup": "Setup Inicial (Inversión)",
    "planes.matrix.audit": "Auditoría Previa",
    "planes.matrix.optional": "Opcional",
    "planes.matrix.agenda": "Agenda + ToDo",
    "planes.matrix.leads": "Gestión de Leads",
    "planes.matrix.docs": "Gestión de Documentos",
    "planes.matrix.icebraker": "Contestador IceBraker",
    "planes.matrix.web_automation": "Automatización Contacto Web",
    "planes.matrix.reminders": "Recordatorios Automáticos",
    "planes.matrix.wa_chatbot": "Chatbot de WhatsApp",
    "planes.matrix.web_chatbot": "Chatbot Web",
    "planes.matrix.web_connect": "WebConnect",
    "planes.matrix.ia_followup": "Seguimientos de Leads (IA)",
    "planes.matrix.analytics": "Analíticas Avanzadas",
    "planes.matrix.internal_ia": "Chatbot de Gestión Interna",
    "planes.matrix.transcriptions": "Transcripción de Reuniones",
    "planes.matrix.funnel": "Funnel de Ventas",
    "planes.matrix.tokens_disclaimer": "* Los planes y módulos incluyen un volumen muy generoso de tokens de IA para un uso diario normal. Si tu empresa requiere un volumen masivo de operaciones, el precio mensual se ajustará de forma transparente en base al coste real de consumo.",
    "planes.audit.title": "¿Cuándo recomendamos una Auditoría?",
    "planes.audit.desc": "Si tienes muy claros tus flujos de trabajo, pasamos directamente al Setup. Pero si tu negocio tiene procesos complejos o desordenados, esta sesión previa nos asegura adaptar la IA a tu realidad operativa.",
    "planes.audit.step1_title": "Mapeo del Flujo",
    "planes.audit.step1_desc": "Nos sentamos contigo para diseccionar paso a paso cómo captas, atiendes y cierras a tus clientes. Identificamos cuellos de botella y tareas manuales repetitivas.",
    "planes.audit.step2_title": "Diseño del Sistema",
    "planes.audit.step2_desc": "Proponemos un rediseño de ese flujo delegando las tareas de poco valor a la IA (como cualificar o registrar datos), manteniendo el toque humano donde realmente importa.",
    "planes.audit.step3_title": "Roadmap de Ejecución",
    "planes.audit.step3_desc": "Salimos de la sesión con un plan claro de qué automatizaciones se van a construir, qué herramientas conectaremos (CRM, Web, WhatsApp) y los plazos exactos.",
    "planes.no_surprises.title": "Sin facturas sorpresa.",
    "planes.no_surprises.subtitle": "Tu cuota mensual lo cubre todo.",
    "planes.no_surprises.what_we_pay": "¿Qué pagamos nosotros?",
    "planes.no_surprises.what_we_pay_desc": "Dentro de tu cuota mensual de Synora, nosotros asumimos los costes de las suscripciones premium necesarias:",
    "planes.no_surprises.what_you_gain": "¿Qué ganas tú?",
    "planes.no_surprises.what_you_gain_desc": "Transparencia y simplicidad contable. Una sola factura al mes de un solo proveedor local.",
    "planes.no_surprises.pay_list.0": "Servidores y Hosting (n8n Enterprise)",
    "planes.no_surprises.pay_list.1": "Consumo de Inteligencia Artificial (Uso estándar)",
    "planes.no_surprises.pay_list.2": "Integraciones (Make/Zapier)",
    "planes.no_surprises.pay_list.3": "WhatsApp Business API",
    "planes.no_surprises.gain_list.0": "Olvídate de gestionar 5 suscripciones",
    "planes.no_surprises.gain_list.1": "Costes predecibles mes a mes",
    "planes.no_surprises.gain_list.2": "Monitorización 24/7 incluida",
    "planes.no_surprises.gain_list.3": "Evolución constante sin pagar más",
    "planes.packs.title": "Packs Especializados",
    "planes.packs.desc1": "Potencia tu plan con",
    "planes.packs.desc2": "verticales específicos",
    "planes.packs.desc3": "diseñados para tu sector.",
    "planes.packs.acquisition_badge": "Pack Captación",
    "planes.packs.acquisition_title": "Captación",
    "planes.packs.acquisition_desc": "Gestión de propiedades, cruce con clientes y publicación centralizada.",
    "planes.packs.intelligence_badge": "Pack Inteligencia",
    "planes.packs.intelligence_title": "Inteligencia",
    "planes.packs.intelligence_desc": "Automatización total del mercado y generación de tasaciones IA.",
    "planes.packs.complete_pack": "Pack Completo",
    "planes.packs.individual_modules": "Módulos Individuales",
    "planes.infrastructure.badge": "Servicios Previos (Pago Único)",
    "planes.infrastructure.title": "Infraestructura y Consultoría",
    "planes.infrastructure.desc": "Servicios opcionales previos al Setup Inicial. Preparamos el terreno construyendo tu web o auditando tus procesos para que la automatización posterior sea un éxito.",
    "planes.infrastructure.web_title": "Web a Medida & CRM Connect",
    "planes.infrastructure.web_desc": "Si tu web actual es un obstáculo, diseñamos desde cero una infraestructura premium optimizada para IA. Conectamos tus herramientas actuales (CRM, Agendas) para que todo fluya hacia tu Dashboard.",
    "planes.infrastructure.web_list.0": "Diseño UX/UI Premium",
    "planes.infrastructure.web_list.1": "Optimización de Conversión (CRO)",
    "planes.infrastructure.web_list.2": "Sincronización de Datos en Tiempo Real",
    "planes.infrastructure.audit_title": "Auditoría & Consultoría ISO 9001",
    "planes.infrastructure.audit_desc": "Analizamos tus procesos actuales y diseñamos el mapa de automatización. Si tu negocio tiene procesos desordenados, esta sesión previa nos asegura adaptar la IA a tu realidad.",
    "planes.infrastructure.audit_list.0": "Mapeo de Procesos Críticos",
    "planes.infrastructure.audit_list.1": "Preparación para Certificación ISO",
    "planes.infrastructure.audit_list.2": "Roadmap de Digitalización",
    "planes.infrastructure.one_time": "Pago Único",
    "planes.custom_advanced.badge": "Ingeniería de Procesos",
    "planes.custom_advanced.desc": "¿Tienes un proceso operativo muy específico o necesitas flujos multi-paso complejos? Diseñamos y mantenemos automatizaciones de alto nivel adaptadas al 100% a tu lógica de negocio.",
    "planes.custom_advanced.investment": "Inversión Estimada",
    "planes.custom_advanced.check": "Consultar Viabilidad",
    "iso.badge_text": "Gracias a esta auditoría obtendrás el",
    "iso.badge_strong": "certificado ISO 9001.",
    "iso.learn_more": "Saber más",
    "iso.title": "Certificado ISO 9001",
    "iso.subtitle": "Sistema de Gestión de Calidad",
    "iso.desc": "La certificación **ISO 9001** es el estándar internacional más reconocido para los Sistemas de Gestión de Calidad (SGC). Durante nuestra Auditoría, no solo mapeamos y optimizamos tus procesos para implementar inteligencia artificial, sino que dejamos documentada toda tu operativa cumpliendo con los estrictos requisitos de esta normativa.",
    "iso.benefits_title": "¿Qué beneficios aporta a tu empresa?",
    "iso.benefit1_title": "Ventaja Competitiva y Confianza",
    "iso.benefit1_desc": "Demuestra a tus clientes y proveedores que trabajas bajo los más altos estándares internacionales de calidad y seguridad.",
    "iso.benefit2_title": "Acceso a Licitaciones y Grandes Cuentas",
    "iso.benefit2_desc": "Es un requisito fundamental (o suma muchos puntos) para trabajar con la Administración Pública o grandes corporaciones.",
    "iso.benefit3_title": "Aumento de Eficiencia",
    "iso.benefit3_desc": "Estandariza tu forma de trabajar. Reduce errores, retrabajos y costes operativos, facilitando además la incorporación de nuevos empleados.",
    "iso.how_it_works": "¿Cómo lo hacemos posible?",
    "iso.how_it_works_desc": "Al analizar en profundidad tus procesos actuales para automatizarlos, generamos la documentación detallada y estandarizada que requiere el sistema ISO. Nosotros construimos los cimientos para que obtengas tu certificación sin esfuerzo extra.",
    "planes.custom_advanced.list.0": "Integración Software Propietario",
    "planes.custom_advanced.list.1": "Flujos de Decisión Autónomos",
    "planes.custom_advanced.list.2": "Mantenimiento y Soporte L1",
    "planes.a_la_carte.badge": "Flexibilidad Total",
    "planes.a_la_carte.title": "Funcionalidades a la Carta (Sin Plan)",
    "planes.a_la_carte.desc1": "No necesitas contratar un plan mensual.",
    "planes.a_la_carte.desc2": "Adquiere cualquier funcionalidad o módulo de forma 100% independiente para digitalizar procesos específicos de tu negocio.",
    "planes.a_la_carte.core": "Core & Gestión",
    "planes.a_la_carte.service": "Atención & Seguimiento",
    "planes.a_la_carte.sales": "Ventas & Captación",
    "planes.a_la_carte.advanced": "Herramientas Avanzadas",
    "planes.guide.title": "¿Cuál es el plan para ti?",
    "planes.guide.subtitle": "Guía rápida según tu momento actual.",
    "planes.guide.step1.badge": "Para Empezar",
    "planes.guide.step1.title": "Organización y Control",
    "planes.guide.step1.desc": "El **Plan Esencial** (99€/mes) es tu puerta de entrada. Ideal para pymes que necesitan control 24/7. Puedes personalizarlo añadiendo módulos sueltos desde +29€/mes.",
    "planes.guide.step2.badge": "El Más Elegido",
    "planes.guide.step2.title": "Automatización y Ventas",
    "planes.guide.step2.desc": "El **Plan Crecimiento** (199€/mes) es nuestra recomendación. Si eres inmobiliaria, acompáñalo del **Pack Captación** (+89€/mes) para dominar el mercado local desde el primer mes.",
    "planes.guide.step3.badge": "Escalabilidad",
    "planes.guide.step3.title": "Infraestructura Total",
    "planes.guide.step3.desc": "Combina el **Plan Pro** (399€/mes) con el **Pack Inteligencia** (+149€/mes) o solicita **Custom Advanced** para tener el ecosistema más avanzado y a medida del sector.",
    "carousel.solutions_for": "Soluciones para",
    "carousel.explore": "Explorar",
    "carousel.inmo.category": "Sector Inmobiliario",
    "carousel.inmo.titleSerif": "Inmobiliarias.",
    "carousel.inmo.description": "Automatizamos la captación, valoración y gestión de exclusivas. Convierte tu agencia en una máquina de cerrar operaciones con datos e inteligencia artificial.",
    "carousel.inmo.f1_title": "Captación 24/7",
    "carousel.inmo.f1_desc": "IA que califica propietarios y programa visitas automáticamente.",
    "carousel.inmo.f2_title": "Valoración Instantánea",
    "carousel.inmo.f2_desc": "Informes de mercado precisos generados en segundos.",
    "carousel.health.category": "Sector Salud",
    "carousel.health.titleSerif": "Clínicas y Centros.",
    "carousel.health.description": "Optimizamos la gestión de pacientes y agendas para centros médicos, dentales y fisioterapia. Automatización total desde la cita hasta el post-tratamiento.",
    "carousel.health.f1_title": "Agenda Inteligente",
    "carousel.health.f1_desc": "IA que gestiona huecos, recordatorios y cancelaciones en tiempo real.",
    "carousel.health.f2_title": "Fidelización Activa",
    "carousel.health.f2_desc": "Seguimiento automático de tratamientos y bonos de sesiones.",
    "carousel.fitness.category": "Sector Fitness",
    "carousel.fitness.titleSerif": "Gimnasios y Centros.",
    "carousel.fitness.description": "Reduce la tasa de bajas con alertas de churn preventivas y automatiza el alta de nuevos socios sin fricciones.",
    "carousel.fitness.f1_title": "Prevención de Bajas",
    "carousel.fitness.f1_desc": "IA que detecta socios en riesgo y activa campañas de retención.",
    "carousel.fitness.f2_title": "Altas Express",
    "carousel.fitness.f2_desc": "Proceso de inscripción y pago 100% digital y automatizado.",
    "carousel.hospitality.category": "Sector Hostelería",
    "carousel.hospitality.titleSerif": "Restaurantes.",
    "carousel.hospitality.description": "Libro de reservas inteligente y gestión de no-shows. Conoce a tus clientes antes de que crucen la puerta.",
    "carousel.hospitality.f1_title": "Cero No-Shows",
    "carousel.hospitality.f1_desc": "Confirmación automática y cobro de fianza en reservas críticas.",
    "carousel.hospitality.f2_title": "Guest Intelligence",
    "carousel.hospitality.f2_desc": "Historial de preferencias y alergias integrado en cada reserva.",
  },
  en: {
    "nav.start": "Home",
    "nav.what_we_do": "What we do?",
    "nav.platform": "Platform",
    "nav.sectors": "Sectors",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact Us",
    "hero.title1": "Your business doesn't need to work more,",
    "hero.title2": "it needs to work alone.",
    "hero.subtitle": "Synora is the automation solution designed for companies that want to grow without complicating their lives. We transform manual processes into intelligent flows.",
    "hero.cta1": "See Solutions",
    "hero.cta2": "Schedule Audit",
    "pillars.title1": "Work less,",
    "pillars.title2": "produce more.",
    "pillars.subtitle": "We transform the broken processes that consume your daily time into intelligent workflows that work autonomously.",
    "pillars.card1.title": "24/7 Automation",
    "pillars.card1.stat": "+10h freed/week",
    "pillars.card1.desc": "Repetitive tasks are managed automatically in the background without manual intervention. Messages, appointments, and alerts on autopilot.",
    "pillars.card2.title": "Absolute Order",
    "pillars.card2.stat": "-40% operational load",
    "pillars.card2.desc": "We transform scattered data into clear dashboards. Reduce your team's operational load by centralizing information.",
    "pillars.card3.title": "Predictive Control",
    "pillars.card3.stat": "0 technical dependency",
    "pillars.card3.desc": "Perfect execution always. Processes are standardized, eliminating human errors and technical dependency on staff.",
    "pricing.badge": "Smart Investment",
    "pricing.title": "Automation Plans",
    "pricing.subtitle": "Scale your business with systems that work for you. No technical complications, just results.",
    "pricing.recommended": "Recommended",
    "pricing.month": "/month",
    "pricing.setup": "Initial setup",
    "pricing.audit": "Recommended Audit (From 200€)",
    "pricing.disclaimer": "* Plans and modules include a generous volume of Artificial Intelligence tokens for standard use. In case of use mass consumption, the price will be adjusted proportionally to real consumption.",
    "pricing.foundational.title": "Infrastructure and Setup (One-time Payment)",
    "pricing.foundational.subtitle": "We build the solid foundation for your automation.",
    "pricing.foundational.web.title": "Custom Web & CRM",
    "pricing.foundational.web.price": "From 349€",
    "pricing.foundational.web.desc": "Your premium showcase ready for AI.",
    "pricing.foundational.iso.title": "Consulting & ISO 9001",
    "pricing.foundational.iso.price": "From 200€",
    "pricing.foundational.iso.desc": "Certified quality and AI processes.",
    "pricing.modules.title": "Automation Modules and Packs",
    "pricing.modules.subtitle": "Add vertical solutions for your sector or individual tools a la carte to power your business.",
    "pricing.modules.all": "See all individual a la carte features",
    "comparison.badge": "Comparison",
    "comparison.title1": "The difference is",
    "comparison.title2": "time.",
    "comparison.without": "Without Synora",
    "comparison.with": "With Synora",
    "footer.title1": "Competitiveness",
    "footer.title2": "without complications.",
    "footer.subtitle": "We are ready to make your business work alone. Are you?",
    "footer.cta": "Contact Synora",
    "footer.rights": "© 2026 Synora Solutions. All rights reserved.",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy",
    "footer.cookies": "Cookies",
    "cookie.title": "Cookies Panel",
    "cookie.desc": "We use cookies to improve your experience. By browsing you accept our policy.",
    "cookie.accept": "Accept all",
    "cookie.settings": "Settings",
    "home.methodology": "Synora Methodology",
    "home.problem_solution": "From problem to solution",
    "home.step01.title": "We detect the jam",
    "home.step01.desc": "We analyze how you work today to identify processes that steal time and generate errors.",
    "home.step02.title": "We design the flow",
    "home.step02.desc": "We define triggers, steps, and exception management. We validate the logic with you.",
    "home.step03.title": "We connect systems",
    "home.step03.desc": "We integrate Synora with your CRM, calendar, and current tools. Without changing software.",
    "home.step04.title": "Go-live",
    "home.step04.desc": "We launch the system and monitor results. Your business starts working by itself.",
    "home.platform.badge": "Your Control Center",
    "home.platform.title1": "A single platform to",
    "home.platform.title2": "rule it all.",
    "home.platform.desc": "Forget about jumping between 10 different tools. Synora Dashboard centralizes your automations, sales funnels, customers, and key metrics in one place.",
    "home.platform.feat1": "Real-time monitoring",
    "home.platform.feat2": "Integration with your current CRM",
    "home.platform.feat3": "Agent and role management",
    "home.platform.cta": "Explore the interactive Dashboard",
    "home.ecosystem.badge": "Industry Ecosystem",
    "home.ecosystem.title1": "Total sectoral",
    "home.ecosystem.title2": "specialization.",
    "home.ecosystem.desc": "Although our technology is transversal, we have designed specific modules for the critical challenges of each industry.",
    "home.sector.inmo.title": "Real Estate",
    "home.sector.inmo.desc": "Owner acquisition and Property Intelligence.",
    "home.sector.clinicas.title": "Medical Clinics",
    "home.sector.clinicas.desc": "AI appointment management and inactive patient recovery.",
    "home.sector.rest.title": "Restaurants",
    "home.sector.rest.desc": "Smart reservation book and Guest Intelligence.",
    "home.sector.gym.title": "Fitness and Sport",
    "home.sector.gym.desc": "Churn prevention and automated member signups.",
    "home.sector.ecomm.title": "E-commerce",
    "home.sector.ecomm.desc": "24/7 customer service and cart recovery.",
    "home.sector.legal.title": "Legal / Firms",
    "home.sector.legal.desc": "Document classification and case triage.",
    "home.sector.custom.title": "Your sector is not listed?",
    "home.sector.custom.desc": "We design custom solutions for any workflow.",
    "home.sector.custom.cta": "Inquire case",
    "home.sector.cta": "See solution",
    "home.coming_soon": "Coming Soon",
    "contact.badge": "Let's talk",
    "contact.title1": "Let's design your",
    "contact.title2": "next leap.",
    "contact.subtitle": "Do you have a process that keeps you awake at night? Tell us and we'll tell you how we can automate it.",
    "contact.form.name": "Name",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.company": "Company",
    "contact.form.companyPlaceholder": "Your company name",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "hello@yourcompany.com",
    "contact.form.message": "How can we help you?",
    "contact.form.messagePlaceholder": "Briefly tell us about your case...",
    "contact.form.submit": "Send message",
    "dashboard.badge": "Operations Center",
    "dashboard.hero.title1": "The brain of",
    "dashboard.hero.title2": "your business.",
    "dashboard.hero.desc": "Centralize, monitor, and scale. Synora Dashboard is not just a control panel, it's the core where artificial intelligence and your processes meet.",
    "dashboard.feat1.title": "24/7 Total Control",
    "dashboard.feat1.desc": "Instant access to all your automated processes. Check the status of your leads, appointments, and operations in real-time from any device.",
    "dashboard.feat2.title": "Smart Analytics",
    "dashboard.feat2.desc": "We don't just show data, we tell you what it means. Identify bottlenecks and growth opportunities with AI-generated reports.",
    "dashboard.feat3.title": "Team Management",
    "dashboard.feat3.desc": "Assign roles, monitor your collaborators' performance, and centralize internal communication without leaving the platform.",
    "dashboard.monitor.badge": "Live Monitoring",
    "dashboard.monitor.title1": "Real-time",
    "dashboard.monitor.title2": "Intelligence.",
    "dashboard.monitor.desc": "Observe how Synora processes every event in your business. From lead entry to sale confirmation, everything happens under your supervision but without your intervention.",
    "dashboard.monitor.latency": "Latency",
    "dashboard.monitor.uptime": "Uptime",
    "dashboard.monitor.events": "Events/day",
    "dashboard.stats.time": "Time Savings",
    "dashboard.stats.leads": "More Leads",
    "dashboard.stats.response": "Average Response",
    "dashboard.stats.time_desc": "We automate repetitive tasks so your team can focus on closing real deals.",
    "dashboard.stats.leads_desc": "Our AI never rests. Captures, filters, and qualifies prospects 24 hours a day, 7 days a week.",
    "dashboard.stats.response_desc": "Response speed is key. Synora serves your customers instantly, ensuring maximum conversion.",
    "dashboard.connect.badge": "Limitless Connectivity",
    "dashboard.connect.title1": "The core that joins",
    "dashboard.connect.title2": "your whole ecosystem.",
    "dashboard.connect.desc": "The dashboard is not a silo. It integrates with every Synora module and pack, plus your current tools, to create a fluid and frictionless workflow.",
    "dashboard.connect.item1.title": "WebConnect",
    "dashboard.connect.item1.desc": "Automatic two-way synchronization between your website and the dashboard. Every lead or change is reflected instantly.",
    "dashboard.connect.item2.title": "Sectoral Modules",
    "dashboard.connect.item2.desc": "Whether for real estate, clinics, or gyms, the dashboard adapts its tools to your industry's needs.",
    "dashboard.connect.item3.title": "API & Webhooks",
    "dashboard.connect.item3.desc": "Connect any external system. If it has an API, Synora can talk to it and centralize its management.",
    "dashboard.ecosystem.title1": "Unlimited",
    "dashboard.ecosystem.title2": "Ecosystem.",
    "dashboard.ecosystem.desc": "Activate only what you need. Our dashboard is a living system that scales with functional blocks ready to be deployed.",
    "dashboard.ecosystem.custom": "Need something custom?",
    "dashboard.ecosystem.custom_cta": "Develop custom module",
    "dashboard.custom.title1": "Made",
    "dashboard.custom.title2": "100% for you.",
    "dashboard.custom.desc": "We don't believe in generic solutions. Each dashboard is configured and personalized according to your company's specific workflows to guarantee maximum performance.",
    "dashboard.custom.cta": "Request customization",
    "dashboard.custom.feat1": "Adaptable",
    "dashboard.custom.feat2": "Integrations",
    "dashboard.custom.feat3": "Zero Technical configuration",
    "dashboard.custom.feat4": "Dual Mode",
    "dashboard.security.title1": "Enterprise-grade",
    "dashboard.security.title2": "security.",
    "dashboard.security.item1.title": "AES-256 Encryption",
    "dashboard.security.item1.desc": "Your data is protected with the industry's most robust encryption standard, both at rest and in transit.",
    "dashboard.security.item2.title": "GDPR Compliance",
    "dashboard.security.item2.desc": "We strictly comply with European data protection regulations for your peace of mind and that of your customers.",
    "dashboard.security.item3.title": "Real-time Backups",
    "dashboard.security.item3.desc": "Automatic replicas in multiple regions to ensure your business never stops.",
    "dashboard.mobile.badge": "Total Mobility",
    "dashboard.mobile.title1": "Your business,",
    "dashboard.mobile.title2": "in your pocket.",
    "dashboard.mobile.desc": "Synora Dashboard has been designed with a \"responsive-first\" approach. Access all the power of your operations center from your smartphone, tablet, or desktop without losing a single functionality.",
    "dashboard.mobile.feat1": "Optimized mobile interface",
    "dashboard.mobile.feat2": "Smart offline mode",
    "dashboard.mobile.feat3": "Real-time push notifications",
    "admin.welcome": "Welcome back.",
    "admin.summary": "Here is a summary of what's happening at Synora.",
    "admin.view_site": "View website",
    "admin.stats.posts": "Published Posts",
    "admin.stats.drafts": "Drafts",
    "admin.stats.visits": "Total Visits",
    "admin.recent_posts": "Recent Posts",
    "admin.logout": "Logout",
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.posts": "Blog Posts",
    "admin.nav.config": "Configuration",
    "planes.hero.title1": "Your scale of",
    "planes.hero.title2": "growth.",
    "planes.hero.desc": "We design plans that adapt to the real volume of your business. No surprises, all included.",
    "planes.matrix.features": "Features",
    "planes.matrix.essential": "Essential Plan",
    "planes.matrix.growth": "Growth Plan",
    "planes.matrix.pro": "Pro Plan",
    "planes.matrix.from": "From",
    "planes.matrix.month": "month",
    "planes.matrix.setup": "Initial Setup (Investment)",
    "planes.matrix.audit": "Prior Audit",
    "planes.matrix.optional": "Optional",
    "planes.matrix.agenda": "Calendar + ToDo",
    "planes.matrix.leads": "Lead Management",
    "planes.matrix.docs": "Document Management",
    "planes.matrix.icebraker": "IceBraker Auto-responder",
    "planes.matrix.web_automation": "Web Contact Automation",
    "planes.matrix.reminders": "Automatic Reminders",
    "planes.matrix.wa_chatbot": "WhatsApp Chatbot",
    "planes.matrix.web_chatbot": "Web Chatbot",
    "planes.matrix.web_connect": "WebConnect",
    "planes.matrix.ia_followup": "Lead Follow-ups (AI)",
    "planes.matrix.analytics": "Advanced Analytics",
    "planes.matrix.internal_ia": "Internal Management Chatbot",
    "planes.matrix.transcriptions": "Meeting Transcription",
    "planes.matrix.funnel": "Sales Funnel",
    "planes.matrix.tokens_disclaimer": "* Plans and modules include a very generous volume of AI tokens for normal daily use. If your company requires a massive volume of operations, the monthly price will be adjusted transparently based on the actual consumption cost.",
    "planes.audit.title": "When do we recommend an Audit?",
    "planes.audit.desc": "If you have very clear workflows, we move directly to Setup. But if your business has complex or cluttered processes, this prior session ensures we adapt AI to your operational reality.",
    "planes.audit.step1_title": "Flow Mapping",
    "planes.audit.step1_desc": "We sit down with you to dissect step by step how you capture, serve and close your customers. We identify bottlenecks and repetitive manual tasks.",
    "planes.audit.step2_title": "System Design",
    "planes.audit.step2_desc": "We propose a redesign of that flow delegating low-value tasks to AI (such as qualifying or registering data), maintaining the human touch where it really matters.",
    "planes.audit.step3_title": "Execution Roadmap",
    "planes.audit.step3_desc": "We come out of the session with a clear plan of what automations will be built, what tools we will connect (CRM, Web, WhatsApp) and the exact deadlines.",
    "planes.no_surprises.title": "No surprise bills.",
    "planes.no_surprises.subtitle": "Your monthly fee covers everything.",
    "planes.no_surprises.what_we_pay": "What do we pay for?",
    "planes.no_surprises.what_we_pay_desc": "Within your Synora monthly fee, we assume the costs of the necessary premium subscriptions:",
    "planes.no_surprises.what_you_gain": "What do you gain?",
    "planes.no_surprises.what_you_gain_desc": "Transparency and accounting simplicity. A single invoice per month from a single local provider.",
    "planes.no_surprises.pay_list.0": "Servers and Hosting (n8n Enterprise)",
    "planes.no_surprises.pay_list.1": "AI Consumption (Standard use)",
    "planes.no_surprises.pay_list.2": "Integrations (Make/Zapier)",
    "planes.no_surprises.pay_list.3": "WhatsApp Business API",
    "planes.no_surprises.gain_list.0": "Forget about managing 5 subscriptions",
    "planes.no_surprises.gain_list.1": "Predictable costs month by month",
    "planes.no_surprises.gain_list.2": "24/7 monitoring included",
    "planes.no_surprises.gain_list.3": "Constant evolution without paying more",
    "planes.packs.title": "Specialized Packs",
    "planes.packs.desc1": "Power up your plan with",
    "planes.packs.desc2": "specific verticals",
    "planes.packs.desc3": "designed for your sector.",
    "planes.packs.acquisition_badge": "Acquisition Pack",
    "planes.packs.acquisition_title": "Acquisition",
    "planes.packs.acquisition_desc": "Property management, client matching and centralized publication.",
    "planes.packs.intelligence_badge": "Intelligence Pack",
    "planes.packs.intelligence_title": "Intelligence",
    "planes.packs.intelligence_desc": "Total market automation and AI appraisal generation.",
    "planes.packs.complete_pack": "Complete Pack",
    "planes.packs.individual_modules": "Individual Modules",
    "planes.infrastructure.badge": "Prior Services (One-time Payment)",
    "planes.infrastructure.title": "Infrastructure and Consulting",
    "planes.infrastructure.desc": "Optional services prior to the Initial Setup. We prepare the ground by building your website or auditing your processes so that the subsequent automation is a success.",
    "planes.infrastructure.web_title": "Custom Web & CRM Connect",
    "planes.infrastructure.web_desc": "If your current website is an obstacle, we design from scratch a premium infrastructure optimized for AI. We connect your current tools (CRM, Calendars) so that everything flows into your Dashboard.",
    "planes.infrastructure.web_list.0": "Premium UX/UI Design",
    "planes.infrastructure.web_list.1": "Conversion Optimization (CRO)",
    "planes.infrastructure.web_list.2": "Real-Time Data Synchronization",
    "planes.infrastructure.audit_title": "Audit & ISO 9001 Consulting",
    "planes.infrastructure.audit_desc": "We analyze your current processes and design the automation map. If your business has messy processes, this prior session ensures we adapt AI to your reality.",
    "planes.infrastructure.audit_list.0": "Critical Process Mapping",
    "planes.infrastructure.audit_list.1": "ISO Certification Preparation",
    "planes.infrastructure.audit_list.2": "Digitalization Roadmap",
    "planes.infrastructure.one_time": "One-time Payment",
    "planes.custom_advanced.badge": "Process Engineering",
    "planes.custom_advanced.desc": "Do you have a very specific operational process or need complex multi-step flows? We design and maintain high-level automations adapted 100% to your business logic.",
    "planes.custom_advanced.investment": "Estimated Investment",
    "planes.custom_advanced.check": "Check Feasibility",
    "iso.badge_text": "Thanks to this audit you will obtain the",
    "iso.badge_strong": "ISO 9001 certificate.",
    "iso.learn_more": "Learn more",
    "iso.title": "ISO 9001 Certificate",
    "iso.subtitle": "Quality Management System",
    "iso.desc": "The **ISO 9001** certification is the most recognized international standard for Quality Management Systems (QMS). During our Audit, we not only map and optimize your processes to implement artificial intelligence, but we also document all your operations complying with the strict requirements of this regulation.",
    "iso.benefits_title": "What benefits does it bring to your company?",
    "iso.benefit1_title": "Competitive Advantage and Trust",
    "iso.benefit1_desc": "Show your clients and suppliers that you work under the highest international quality and safety standards.",
    "iso.benefit2_title": "Access to Tenders and Large Accounts",
    "iso.benefit2_desc": "It is a fundamental requirement (or adds many points) to work with the Public Administration or large corporations.",
    "iso.benefit3_title": "Efficiency Increase",
    "iso.benefit3_desc": "Standardize your way of working. Reduce errors, rework and operating costs, also facilitating the onboarding of new employees.",
    "iso.how_it_works": "How do we make it possible?",
    "iso.how_it_works_desc": "By deeply analyzing your current processes to automate them, we generate the detailed and standardized documentation required by the ISO system. We build the foundations so that you obtain your certification without extra effort.",
    "planes.custom_advanced.list.0": "Proprietary Software Integration",
    "planes.custom_advanced.list.1": "Autonomous Decision Flows",
    "planes.custom_advanced.list.2": "Maintenance and L1 Support",
    "planes.a_la_carte.badge": "Total Flexibility",
    "planes.a_la_carte.title": "A la Carte Features (Without Plan)",
    "planes.a_la_carte.desc1": "You don't need to hire a monthly plan.",
    "planes.a_la_carte.desc2": "Acquire any functionality or module 100% independently to digitalize specific processes of your business.",
    "planes.a_la_carte.core": "Core & Management",
    "planes.a_la_carte.service": "Service & Follow-up",
    "planes.a_la_carte.sales": "Sales & Acquisition",
    "planes.a_la_carte.advanced": "Advanced Tools",
    "planes.guide.title": "Which plan is for you?",
    "planes.guide.subtitle": "Quick guide according to your current moment.",
    "planes.guide.step1.badge": "To Get Started",
    "planes.guide.step1.title": "Organization and Control",
    "planes.guide.step1.desc": "The **Essential Plan** (99€/month) is your gateway. Ideal for SMEs that need 24/7 control. You can customize it by adding individual modules from +29€/month.",
    "planes.guide.step2.badge": "Most Popular",
    "planes.guide.step2.title": "Automation and Sales",
    "planes.guide.step2.desc": "The **Growth Plan** (199€/month) is our recommendation. If you are a real estate agency, accompany it with the **Acquisition Pack** (+89€/month) to dominate the local market from the first month.",
    "planes.guide.step3.badge": "Scalability",
    "planes.guide.step3.title": "Total Infrastructure",
    "planes.guide.step3.desc": "Combine the **Pro Plan** (399€/month) with the **Intelligence Pack** (+149€/month) or request **Custom Advanced** to have the most advanced and customized ecosystem in the sector.",
    "carousel.solutions_for": "Solutions for",
    "carousel.explore": "Explore",
    "carousel.inmo.category": "Real Estate Sector",
    "carousel.inmo.titleSerif": "Real Estate Agencies.",
    "carousel.inmo.description": "We automate acquisition, valuation, and exclusive management. Turn your agency into a deal-closing machine with data and AI.",
    "carousel.inmo.f1_title": "24/7 Acquisition",
    "carousel.inmo.f1_desc": "AI that qualifies owners and schedules visits automatically.",
    "carousel.inmo.f2_title": "Instant Valuation",
    "carousel.inmo.f2_desc": "Accurate market reports generated in seconds.",
    "carousel.health.category": "Health Sector",
    "carousel.health.titleSerif": "Clinics and Centers.",
    "carousel.health.description": "We optimize patient and schedule management for medical, dental, and physiotherapy centers. Total automation from appointment to post-treatment.",
    "carousel.health.f1_title": "Smart Schedule",
    "carousel.health.f1_desc": "AI that manages slots, reminders, and cancellations in real time.",
    "carousel.health.f2_title": "Active Loyalty",
    "carousel.health.f2_desc": "Automatic follow-up of treatments and session vouchers.",
    "carousel.fitness.category": "Fitness Sector",
    "carousel.fitness.titleSerif": "Gyms and Centers.",
    "carousel.fitness.description": "Reduce churn rate with preventive alerts and automate new member signups without friction.",
    "carousel.fitness.f1_title": "Churn Prevention",
    "carousel.fitness.f1_desc": "AI that detects at-risk members and triggers retention campaigns.",
    "carousel.fitness.f2_title": "Express Signups",
    "carousel.fitness.f2_desc": "100% digital and automated registration and payment process.",
    "carousel.hospitality.category": "Hospitality Sector",
    "carousel.hospitality.titleSerif": "Restaurants.",
    "carousel.hospitality.description": "Smart reservation book and no-show management. Know your customers before they walk through the door.",
    "carousel.hospitality.f1_title": "Zero No-Shows",
    "carousel.hospitality.f1_desc": "Automatic confirmation and deposit collection for critical reservations.",
    "carousel.hospitality.f2_title": "Guest Intelligence",
    "carousel.hospitality.f2_desc": "History of preferences and allergies integrated into each reservation.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "es" || savedLang === "en")) {
      setLanguageState(savedLang);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): any => {
    return translations[language][key] || key;
  };

  // Use the provider even when not mounted to avoid context errors in children
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
